import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import HomeLayout from '@/components/layout/HomeLayout';
import HomeComponent from "../components/page/Home/Home"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeLayout>
         <div className='bg-[#F5F5F5] mt-[8.5rem] md:mt-[5rem]'>
            <HomeComponent/>
         </div>
           
      </HomeLayout>
    </>
  )
}
